# Site settings
title: AiAutoMatrix
description: A Hub for connecting Ai & automation solutions into your Business. 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.willianjusten.com.br
# User settings
username: AiAutoMatrix
user_description: At Ai-AutoMatrix, we are at the forefront of the AI revolution, empowering businesses to transcend traditional limitations. Discover a world where cutting-edge technology meets innovative solutions, enhancing efficiency, engagement, and profitability. Step into the future of automation with us!
user_title: Garret (Bigtimetreat) Friesen
email: AiAutomatrix@outlook.com
linkedln_username: Garret Friesen
facebook_username:  Bigtimetreat
instagram_username: Bigtimetreat
github_username:  Bigtimetreat
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
