# Site settings
title: Ai AutoMatrix
description: A Hub for connecting Ai & automation solutions into your Business. 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.willianjusten.com.br
# User settings
username: Bigtimetreat
user_description: At AI AutoMatrix, we are at the forefront of the AI revolution, empowering businesses to transcend traditional limitations. Discover a world where cutting-edge technology meets innovative solutions, enhancing efficiency, engagement, and profitability. Step into the future of automation with us!
user_title: Garret Friesen Customizes Ai & Automations
email: AiAutomatrix@outlook.com
twitter_username: Bigtimetreat
github_username:  Bigtimetreat
gplus_username:  Bigtimetreat
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
