# Site settings
title: GarretGPT
description: A Hub for connecting Ai & automation solutions into your Business. 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: GarretGPT
user_description: At AI AutoMatrix, we are at the forefront of the AI revolution, empowering businesses to transcend traditional limitations. Discover a world where cutting-edge technology meets innovative solutions, enhancing efficiency, engagement, and profitability. Step into the future of automation with us!
user_title: Garret Friesen Ai & Automations
email: GarretGPT@outlook.com
twitter_username: lorem_ipsum
github_username:  AiAutomatrix
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
