# Site settings
title: Ai Automatrix
description: A Hub for connecting Ai & automation solutions into your Business. 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.willianjusten.com.br
# User settings
username: Ai Automatrix
user_description: At AI Automatrix, we specialize in developing and deploying custom ChatGPT4o bots tailored to your unique needs. Our bots come equipped with diverse capabilities, thanks to our expertise in creating custom plugins, web integrations, and automation solutions. Each bot is designed to interact seamlessly with you and your environment, leveraging the latest cutting-edge technology from OpenAI and the Botpress LLMz Engine. Our passionate team at AI Automatrix is dedicated to delivering personalized software solutions that push the boundaries of what's possible in AI.
user_title: Custom AI Bot Marketplace
email: AiAutomatrix@outlook.com
facebook_username:  Bigtimetreat
instagram_username: Bigtimetreat
github_username:  Bigtimetreat
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
